name: chatterbox-env
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.11
  - pip

  # GPU-версии PyTorch
  - pytorch=2.6.0
  - torchvision=0.20.1
  - torchaudio=2.6.0
  - pytorch-cuda=12.1

  - pip:
      - -e .
      - gradio==5.44.1
      - librosa==0.11.0
      - transformers==4.46.3
      - diffusers==0.29.0
      - resemble-perth==1.0.1
      - conformer==0.3.2
      - safetensors==0.5.3
      - pkuseg==0.0.25
      - pykakasi==2.3.0
      - s3tokenizer==0.2.0
